# Qualitative designs 

In this chapter we are comparing and contrasting quantitative and qualitative designs to help you with the gear shift.

These are two very different ways to approach data collection and consequently, the type of data they yield is very different. It is important to recognise that not one method is "superior" or easier than the other - the paradigm you choose depends on the type of questions you want to answer.

Complete the activities below to familiarise yourself with the key differences between the two methodologies.

## Activity 1: Differences between qualitative and quantitative designs


|Quantitative             |Qualitative           |
|-------------------------|----------------------|
|Numbers used as data     |Words (written/spoken) and images used as data.|
|Seeks to identify relationships between variables to explain or predict with the aim of generalising findings to a wider population|Seeks to understand and interpret more local meanings. Recognises data as gathered in a context. *Sometimes* produces knowledge that contributes to more general understandings|
|Generates "shallow" but broad data: not a lot fo complex detail obtained from each participant but lots of participants take part to generate statistical power|Generates narrow but rich data - "thick descriptions" - detailed and complex accounts from each participant, not many participants|
|Seeks consensus, norms or general patterns, often aims to reduce diversity of responses to an average response|Tends to seek patterns but accommodates and explores difference and divergence within the data|
|Tends to be theory-testing and deductive|Tends to be theory generating and *inductive* (working up from the data)|
|Values detachment and impartiality (objectivity)|Values personal involvement and partiality (subjectivity, reflexivity)|
|Has a fixed method (harder to change focus when data collection has begun)|Method is less fixed (can accommodate a shift in focus in the same study)|
|Can be completed quickly|Tends to take longer to complete because it is interpretative and there is no formula|

Look at the table above and write down answers for the following questions:

  + What might a 'typical' quantitative study look like? What kind of data might be collected? What would be the aim of the study? What might your sample look like?
  + What might a'typical' qualitative study look like? What kind of data might be collected? What would be the aim of the study? What might your sample look like?
  + What type of research question might be best answered with a quantitative design? 
  + What type of research question might be best answered with a qualitative design? 
  
## Activity 2: Research designs quiz

Choose whether a quantitative or qualitative design is most appropriate for each of the following studies. Why did you choose each option?

1. Angela is conducting a study exploring the experiences of people currently experiencing mental ill health. She is interested in a) better understanding what people with mental ill health experience day-to-day, and b) exploring the support mechanisms that are in place

This study is more likely to be: `r mcq(c(answer = "Qualitative", "Quantitative"))`

::: {.callout-caution icon=false collapse="true"}
## Explain the answer

This study would be best conducted as a qualitative study - the researcher is interested in exploring the experiences of people
:::

2. John is conducting a study where he is measuring whether the amount of sleep that children get is related to their cognitive performance in class. He asks the children to wear a sleep tracker to bed, so he can see when they are sleeping and when they are awake.

This study is more likely to be: `r mcq(c("Qualitative", answer = "Quantitative"))`

::: {.callout-caution icon=false collapse="true"}
## Explain the answer

This study would best be conducted as a quantitative study - the data will be quantified in numbers
:::

3. Sally is conducting a study where she is interested in the effects of violence on TV on children.

This study is more likely to be: `r mcq(c(answer="Qualitative", answer= "Quantitative"))`

::: {.callout-caution icon=false collapse="true"}
## Explain the answer
This study could be either quantitative or qualitative depending on how it's set up - if the researcher is interested in a causal relationship and measures the effects numerically, the study would be quantitative. However, if the researcher for example does interviews with parents and wants to find out their experiences and perceptions more in depth, the study could also be qualitative.
:::

4. James is conducting a study where he wants to better understand motivations for smoking among teenagers.

This study is more likely to be: `r mcq(c(answer= "Qualitative", "Quantitative"))`

::: {.callout-caution icon=false collapse="true"}
## Explain the answer
This study would probably best be conducted as a qualitative study - the researcher is looking at the motivations of the participants. However, it could also possibly be a quantitative study, if the motivations are measured and quantified on a numeric scale instead of text data.
:::

5. Elaine is conducting a study exploring whether the amount of studying done in preparation for an exam predicts exam performance.

This study is more likely to be: `r mcq(c("Qualitative", answer= "Quantitative"))`

::: {.callout-caution icon=false collapse="true"}
## Explain the answer
This study would be quantitative - the researcher is interested in a causal relationship between the variables, which you cannot achieve with a qualitative design.
:::
