# Data collection

This chapter runs through some of the practical issues you need to think about when collecting data for a qualitative study. Do the activities below on your own and then discuss your answers with your group.

## Considering ethics

**Informed consent**

Before and data collection takes place, you must provide your participants with an information sheet and consent form (see [chapter 5: Ethics](https://wtoivo.github.io/RM2-ODL-quali-book/ethics-rigour-and-reflexivity.html) for more detail!) 

You must give everyone participating the Information sheet and consent form before the focus group/interview takes place. Completed consent forms should be returned to the researcher and you should verbally confirm consent before you start any data collection. In a survey, participants should complete consent form before seeing any survey questions.

**Confidentiality in Focus groups**

Remember that everyone (both those participating and running) the focus group have a responsibility to maintain confidentiality of the discussion. 

Discuss some 'ground rules' at the start with the group, and also go through the Information Sheet and consent form at the start, to ensure everyone is aware of their responsibilities. You may also want to include an ice breaker to make your participants feel more comfortable.

## Focus group structure

There are a number of stages to a focus group, and it's not always exactly the same, but here is an example structure for a focus group:

  * **Stage 1: Setting the scene.** The topic of the project should be introduced by the facilitator, and everyone agrees to take part. It must be made clear to the people in your focus group a) that they do not have to answer any questions that they do not feel comfortable with, b)  highlight that the session will be recorded (if conducting your study online, also make sure to let your participants know they have a choice to have their camera on or off, but that the mic must be used), c) what will happen with the recordings (i.e. that they will be kept safe on University-approved servers and the transcript anonymised), d) that everyone has a responsibility to maintain confidentiality of the topics discussed in the group and e) that they are free to leave the session at any time. Run through the Information Sheet and Consent Form here, and discuss any ground rules you have. I would also raise the point here that there are a few questions to get through, and therefore you might have to step in to help manage time. 
  * **Stage 2: Recording.** Remember to start recording and let your participants know when you do it. This is very important. 
  * **Stage 3: Introductions.** Go around the table and ask everyone to introduce themselves. Start with yourself and the note-taker first. Everyone should state their first name clearly. 
  * **Stage 4: Ice-breaker.** Ask a warm-up question or ice-breaker. The aim is to allow participants to introduce themselves, ensure everyone understands the procedure, and to encourage people to feel comfortable talking. Previous projects have used photos, cartoons, and media, or asked participants to generate meanings of the terms used in the discussion (e.g., “poor sleep”,”well-being”) to get people talking.
  * **Stage 5: Discussion.** This is where you ask your main questions, and follow-up questions. It is a good idea to prepare around five or six main questions, and perhaps highlight three or four that are most important to focus on. The discussion may follow a different order to that on the focus group schedule  - this is fine. 
  * **Stage 6: Facilitating the discussion.** The facilitator should be prepared to help steer conversation back on track, and balance discussion so that everyone gets a chance to contribute. Have a few specific prompts that relate to each question and/or some general prompts to keep the discussion flowing.  What are you going to do if no-one participates? Or if one person is contributing?  For example… “has anyone else had a similar experience? Does anyone have a different view?” At the same time be ethical and avoid targeting individual people. Give participants the opportunity to describe their interpretations and take ownership.  E.g.,  “How would…make you feel”, “Have you ever noticed that…” “Think back to when…”,  “What was most important to you about…?” 
  * **Stage 7: Ending the discussion.** It's good to end the discussion by going round the group and asking each participant if they have anything they want to add to the discussion/sum up their thoughts on what was discussed.Remember to allow focus group members the chance to confirm/withdraw consent for their anonymised contributions to be used.
  
  
## Facilitation and note-taking

**Facilitation/moderation**

The facilitator (sometimes also known as the moderator) will be the person taking the lead during the focus group. They will be the one asking the questions of the participants, and the one facilitating the discussion. As you are aiming to mimic a naturalistic conversation, you have to build rapport. Ensure you allow everyone time to introduce themselves, and contribute to the ice-breaking phase by saying a bit about yourself. 

A good facilitator shares the perspective of the people they are talking to throughout the focus group. The moderator should not be listening out for good quotes and should not be thinking about what to analyse. The role of the facilitator is to listen to the participants, and understand their points of view.

**Note-taking**

It is a good idea to have a note-taker there. Hopefully there will be no IT issues that mean that the recording doesn't work! Therefore, the note-taker should remind the facilitator about recording if required, and note down any impressions/initial thoughts around themes/good quotes. Also, you could note down how well the questions worked  - were there any that participants didn't understand? It should be clear from the recording who is contributing when; it is useful to note down here and there who is speaking at various points, to ensure it matches up later on.

## Facilitating focus groups: How to manage the group?

Focus groups are designed to be an informal discussion in a moderated setting. This allows for the data collection to be flexible and occur in a collective, more natural way  - however, moderating a discussion in a group setting can also be challenging. Below we have some top tips for how to manage focus groups.

1. Make sure your participants are comfortable: establish ground rules and expectations at the start, ensure that you are interested in their perceptions and experiences and that there are no right or wrong answers, start with an ice-breaker to warm your participants up and make sure nobody is put on the spot and participants don't feel pressured to answer anything they do not wish to answer.

2. Manage the conversation effectively: make sure all participants have the opportunity to contribute if they wish and one participant doesn't dominate the whole conversation, ensure that conversation doesn't stray off topic or get stuck on one topic for too long. Give prompts if the participants struggle to get started on a question.

3. Stay neutral and *listen*: be careful not to provide your own opinion or views (this is surprisingly easy to do accidentally!) - this is about your participants and their experiences. Focus on listening to the participants and clarifying/prompting further if needed, give your participants time to gather their thoughts  (learn to be comfortable with silent moments and don't fill them in with your opinions).

View below some situations you may encounter when running a focus group: before checking the answer, have a think how you would manage these scenarios and discuss the answers with your group.

  1. One/some participants are very quiet and one participant dominates the conversation
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

* The ice-breaker/easy opening questions are perhaps most important for quieter members of the group, to help make them feel more comfortable.
  * If you are running the focus group online, it might be a good idea to use the Raise hand feature  - this would allow quieter members to show that they want to contribute, but without trying to gauge when to jump in the conversation. You can then take points in order of when they raised their hands.
  * If some people have contributed to part of the discussion and others haven't, open it up to the rest by asking if anyone who hasn't responded yet has anything to add. However, don't put people on the spot by asking them directly. 
  * Make sure to distribute turns equally
  
:::

  2. The discussion is stuck on one topic
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * Remind the members of the group that there are a number of different questions to explore, and that you are mindful of time, so it might be  best to leave that topic for now, and you can return if there's time at the end.
  
:::


  3. The discussion goes off topic

::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * The facilitator has to be mindful of this and be ready to steer the conversation back on topic if needed.
  * Remind the members of the group that there are a number of different questions to explore, and that you are mindful of time.
  * Gently remind participants of the question that was asked. If running the FG online, you may wish to put your questions on the chat or present them with screen sharing so the participants can see the question.

:::


  4. Participants are not comfortable answering the questions in the language the focus group is conducted in
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * Send questions in advance to your participants so they can prepare
  * Consider if the FG could be conducted in a different language (however, be mindful that this creates additional work with transcription and translations and requires the facilitator to be fluent in the language)
  * Give participants time to think and answer, and focus on making everybody feel comfortable at the start of the FG.
  
:::


  5. One participant looks uncomfortable and does not contribute
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * Try to create opportunities for everybody to speak, but remember that you should not point fingers at individual participants
  * You cannot force anybody to speak, and sometimes participants might feel uneasy. 
  * Remember that they don't need to answer any of the questions if they don't want to  - it is unethical to force your participants to answer.

:::


  6. Nobody answers the question you asked
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * Remember that this is the first time the participants may see the question, and they may need time to gather their thoughts
  * Consider sending questions to your participants in advance so they know what to expect.
  * Don't be uncomfortable with a bit of awkward silence (particularly if running your FG online) and don't fill the space with your opinions - let the participants take the lead.
  * Prepare prompts/probes that you can ask to help the participants get started.
  * You can ask if anybody would like to go first (don't put an individual participant on the spot)

:::

  7. You are not sure what the participant meant/the participant answers very shortly
  
::: {.callout-caution icon=false collapse="true"}  

## Suggested Solutions

  * You can ask if the participant would like to clarify the aspect of the answer you are not sure about.
  * You can ask the participant to elaborate further (they may not want to, which is fine!). If you do this, make sure that you are specific about what you want them to elaborate on (for example, "that's really interesting, would you want to tell me a little bit more about why you think XXX?)
  * If the participant does not know how to elaborate, you can ask if anybody else wants to add anything. Sometimes this will prompt the participant to build on their answer as a response to what the other participants are saying.

:::

## Facilitating interviews

Interviews are very different to focus groups, as the data collection is typically set up in a one-on-one situation. This means the types of questions you should ask, the types of answer you are likely to get, and the practical issues are quite different to focus groups. Here are some top tips for how to conduct an interview. 

  * Make an effort to develop rapport and make the participant feel comfortable.
  * If you are doing a sensitive topic, pay attention to how your participant is presenting and ask them if they need a break or if they would like to continue.
  * Focus on the person rather than taking notes - are you giving them encouragement to keep speaking (e.g. nods etc.)?
  * If doing a semi-structured interview, pay attention to whether the participant brings something up that could/should be followed up with an addional question
  * Not all interviews will be the same length  - some people are very concise in how they answer whereas others talk a lot more so the overall interview length will vary
  * Try to end on a positive question if you can - it can help to lift the mood for the participant and leave them in a good place
  
## GDPR-compliance and data management

GDPR: general data protection regulation. It is the most up to date data protection law and your data collection and storage must comply to the GDPR principles. 

See the University guidelines on handling confidential data  https://www.gla.ac.uk/myglasgow/it/informationsecurity/confidentialdata/. You can read more about GDPR here: https://www.gla.ac.uk/myglasgow/dpfoioffice/gdpr/

Make sure that:

  * You have a data management plan in place before data collection (how and where are you storing the data, who will have access to it, how long do you need to store it for, what steps of confidentiality and anonymisation are you taking?)
  * Participants are made aware of your data management plan prior to any data collection in the information sheet and consent form
  * Data should be retained until after completion of the project on a password-protected encrypted drive and a secure database accessible only to the research team
  * Only use University-approved systems to collect, manage and store data  - **do not use external providers (such as Google or Dropbox)**, as they may not be GDPR compliant
  * If you share the data, your participants should be informed about this prior to taking part, and you should only share the anonymised data files 
  * **Do not share data via social media, Google drive or personal email which is not secure.**

## OPTIONAL: Research skill session - data collection

Ashley has recorded **optional** research skills sessions on different aspects of qualitative research. These sessions take a little bit deeper dive into some of the topics and may be particularly useful if you are planning on doing a qualitative dissertation next year. 

[Watch the video here](https://echo360.org.uk/media/1f84181c-364e-47e3-a61e-415e4ec5a368/public?autoplay=false&automute=false&startTimeMillis=0)

### General tips

  * Be organised  - get ethics in early etc., keep track of potential participants
  * Think through all the different steps involved as you will need to refer to this in your ethics application  - how do you plan to recruit, collect the data, store the data? Before you start collecting data, it would be good to have a checklist with everything you need to consider
  * Only collect the demographics that you need  - if you don't need to know how many siblings they have or what time they go to bed, then don't ask for that information
  * Be sensitive to who your participants are - you might ask different questions in a focus group (where people are in front of others) than you would in an online questionnaire (where it is easier to withdraw if uncomfortable).
  * Think about how you keep that data safe/anonymous
  * Know in advance how many participants you need
  * Know how you plan to analyse the data
  * Consider what you can do to make the experience as
comfortable as possible for participants (e.g. sending out questions in advance is particularly helpful for neurodivergent people/people who do not speak English as a first language).
  * For interviews and focus groups - reassert consent before you start & always remember to press record! Also it's normal to feel a bt nervous - try to enjoy the process!
  * For all, pilot the questions you ask - make sure that people take from them what you think
  * When recruiting, think about who your target group is and it's good to justify why you are looking for a particular demographic. For example, do you definitely require someone to have a particular diagnosis?
  
### Practicalities of running focus groups

  * Establish ground rules - esp. confidentiality
  * Set expectations - ask participants to respond to each other rather than each person individually responding to the question (if possible, this is not always the case)
  * Moderator has to manage the group as best they can
  * Wrapping things up.
  * Can be helpful to have a notetaker to note down anything interesting/if doing it in person, to note down order that people speak in. Allows the moderator to focus on discussion

**Tricky situations**

  * How do you develop rapport/make people feel more
comfortable?
  * How do you manage tricky dynamics within a group?
  * What if no-one speaks/one person dominates?
  * What if people go off topic?
  * How to keep people to time?
  * Giving everyone who wants it an opportunity to speak - if online could ask people to raise their hand
  
  
### Practicalities of running interviews

Some of the things that we discussed in focus groups are
relevant here, but specifically when thinking about interviews:

  * Try to develop rapport and make the participant feel
comfortable
  * Try to focus on the person rather than taking notes - are you giving them encouragement to keep speaking (e.g. nods etc.)?
  * If doing a semi-structured interview, try to notice if the participant brings something up that could/should be followed up with an additional question
  * It's usual for some interviews to be shorter than others - some people are very concise in how they answer whereas others talk a lot more (and this may be on topic or not)
  * Be aware of how someone is presenting - this is less relevant for coursework and more for future projects - if you are doing quite a sensitive topic, it's good practice to reassert consent and to ask people if they need a break for a little while/if they are okay to continue.
  * Try to end on a positive question if you can - it can help to lift the mood for the participant and leave them in a good place
  
### Practicalities of running qualitative surveys

  * Think about whether there would be any possibility for the questions to be misinterpreted - you won't have a chance to correct people if they interpret something wrong (this is where doing a pilot can be useful)
  * Try not to have too many questions  - what are the key things you want to know? People will be less likely to respond with long, in depth answers if there are a lot of questions to answer.
  * It might be good to give an indication of how many questions they have to go through.
  * Easier to keep data anonymous than it is with other forms of data collection above - however still be sensitive to locations, names, personal experiences as these will have to be anonymised.
