# Ethics, rigour and reflexivity

This chapter will help you to consider ethics and reflexivity in qualitative research.

## Ethics

This section will talk you through the ethical considerations you need to conduct qualitative research. As you remember from RM1, every time we conduct research with human participants, we have to think carefully about the potential impact of our research and we must adhere to the [BPS Code of Human Research Ethics](https://cms.bps.org.uk/sites/default/files/2022-06/BPS%20Code%20of%20Human%20Research%20Ethics%20(1).pdf). Some of the ethical issues are common to both quantitative and qualitative research (for example, informed consent and the right to withdraw), but due to the nature of qualitative data, there are certain aspects we need to be particularly mindful about.

### General ethical considerations

These are some of the things we **MUST** take into account when conducting research on human participants:

  * Possible risks to participants (physical and/or psychological)
  * The elimination or minimization of risks
  * Justifying risks in terms of the scientific value of the results
  * Ethical approval prior to the study
  * The right to withdraw
  * Informed consent
  * Debriefing and aftercare of participants (especially with deception)
  * Anonymity and appropriate data management
  
### Activity 1: Identify potential ethical issues

Before reading on, try to think what ethical issues each of these elements of qualitative research might have:

  * Research questions and interview/focus group questions
  * Data collection
  * Recording of interviews/focus group
  * Anonymity
  * Confidentiality
  
**1. Research questions and interview/FG questions**  
  
*This might look like:* In qualitative research, we often ask about someone’s lived experience, or their motivations, or a belief they have. This is quite different to quantitative research where data comes in as numbers and in that sense is less personal. 

*Why might this be an issue:* Qualitative research tends to be on topics where we ask people to be vulnerable and open themselves up to us as researchers. If we don't frame this correctly, our interview schedule might contain questions that are inappropriate and uncomfortable for the participants. 

**2. Data collection**

*This might look like:* Data collection is much less likely to be anonymous, as typically in-person or online focus groups or interviews are held. Samples are small, and participants may already be known to the researcher.

*Why might this be an issue:*  There are possible issues of confidentiality, anonymity (these will be discussed further down) and bias. Our preconceptions might affect the way we frame the questions, how we interact with participants in the focus group, and how we interpret the data.

**3. Recording of focus groups/interviews**

*This might look like:* The majority of the time, focus groups and interviews are recorded (either audio + video or audio only). This means that the 'raw' data - as it were - is identifiable. In contrast, data for quant studies are often collected anonymously. 

*Why might this be an issue:* Data should **always** be kept safe and secure. However, with qualitative data, there is a real risk that individual people could be identified from a recording of them. This  means that dealing with the recordings in a safe and secure way are of utmost importance, and that participants cannot be identified from transcripts.

**4. Anonymity **

*This might look like:* In quantitative research, we tend to report summary statistics from groups, and therefore it’d be quite unusual to be able to identify a single participant from the data. With qualitative, it’s a bit different. We collect people’s words and experiences.

*Why might this be an issue:* It is easier to identify someone from the words they use, and the situations and circumstances they describe. 

**5. Confidentiality**

*This might look like:* In a focus group or interview, people might be very open with us, and tell us things about their life, and the lives of others. 

*Why might this be an issue:* We have a duty of care to keep anything that comes out in a focus group/interview confidential (unless they disclose a crime or someone is judged to be at risk). It’s also vital that the rest of the focus group members keep the information confidential too.

**How would you mitigate these issues?**

### Activity 2: Ethics in published studies

Look at the methods sections of these studies and try to identify how they have addressed ethical issues

  * [Scott et al., 2019](https://www.sciencedirect.com/science/article/pii/S2352721819301457#s0010)
  * [Sutton & Stack, 2013](https://academic.oup.com/bjsw/article/43/3/596/1636960?login=true)
  * [Robertson & Simmons, 2015](https://journals.sagepub.com/doi/pdf/10.1068/p7833)
  
  
### Activity 3: Information sheet and constent form

Take a look at the (slightly modified) Information sheet and Consent form from a qualitative survey study that had ethical approval from the University. Can you identify where and how the principles listed in the General ethical considerations and Activity 1 are discussed?

#### Information sheet

How do perceived language barriers affect the teachers’ experience teaching international students in higher education

**Invitation**
My name is XX, and I am a student at the University of Glasgow. This study is conducted as a part of my MSc Psychological Studies Dissertation project. You are invited to take part in this study because you are currently teaching international students at a UK-based university. Before you decide to take part, it is important for you to understand why the research is being done and what it will involve. Please take time to read the following information carefully and discuss it with others if you wish. If you would like further details about the study before deciding whether you want to participate, please get in touch with us via email (XX@student.gla.ac.uk). 

**Brief Summary** 
We are looking to learn more about higher education teachers' perceptions and experiences of language barriers. We are recruiting people who are currently teaching and/or supervising international students in a UK-based university. To understand your experience, opinions and thoughts on this topic, we are conducting the study through an online qualitative survey. Some issues which we are interested in learning more about include: 1) the impact of language barriers on teaching and supporting students who speak English as a second language; 2) how teaching staff perceive language barriers affecting them and their students; 3) possible ways to bridge the language barriers at different levels.

**What’s involved if I agree to take part?**
We want to support you in deciding whether this research study is suited to you - if upon reading this information sheet, you have more questions, please do not hesitate to contact us. If you choose to take part, we will ask you to provide informed consent, after which you will be asked to complete the survey, which consists of two parts: a brief demographic questionnaire, and six open-ended main questions about your experiences of language barriers in your teaching. The survey should take no longer than 40 minutes to complete, and you may take a break at any point if you wish. Because the data will be analysed using qualitative methods, we ask you to provide a comprehensive account of your experiences, but only to provide as much or as little detail as you feel comfortable sharing. Anonymised (see below) quotes from your responses may be used in the dissertation and other future dissemination to illustrate the findings. If you choose to withdraw from the study at any point, you may do so by simply closing your browser. 

**Confidentiality: Ways to protect your identity and data** 
We do not want to reveal any personal information about yourself or your colleagues as part of this research. Your responses are recorded completely anonymously through Microsoft Forms and your name will not be recorded anywhere. Prior to the data analysis, all responses will be screened and further anonymised in case you have provided information which may be identifiable (such as specific course names or institutions). We will take the following steps to make sure that your personal information and particular details of your experiences are not shared. 

  * Your data will be assigned an anonymous participant ID automatically and password protected on a secure server
  * Changing any names, places or organisations you write in your answers.
  * All the research data will be securely stored to comply with the General Data Protection Regulation (2018) and only made accessible to future researchers in a form which protects individual, personal information.

**What are the possible disadvantages and risks of taking part? **
The materials do not involve anything that would affect you in a negative way – as explained above, you may share as much or as little detail about your experiences as you feel comfortable doing. You are also free to withdraw from the research by closing your browser at any point without giving any reason why. 

**Who is organising this research?**
This research is being conducted as part of an MSc Dissertation. The research is supervised by Dr Wilhelmiina Toivo, Wilhelmiina.toivo@glasgow.ac.uk and the research has been granted ethical approval from the University of Glasgow.  If you would like further details about the study before deciding whether you want to participate, please get in touch with us via email. Many thanks, XX,

#### Consent form

**Title of Project:** How do perceived language barriers affect the teachers’ experience teaching international students in higher education?

**Researcher:**  XX, (Supervisor Wilhelmiina Toivo)

If you agree to participate in this study, then please read the following statements and indicate your consent by ticking the boxes for each statement 

  * I have read the Information Form for participants and so understand the procedures and have been informed about what to expect.
  * I agree to participate in this study, which aims to investigate how perceived language barriers affect university teachers’ experiences teaching and interacting with international students who speak English as their foreign language.
  * I understand that my participation in this study is voluntary, and that I can withdraw from the study, at any time and for any reason, by closing the browser.
  * I understand that my participation in this project is for the purposes of research and is in no way an evaluation of me as an individual.
  * I understand that any information given in the investigation will be made and kept anonymous and will remain confidential and no information that identifies me will be made publicly available.
  * I understand that anonymous quotes from my responses may be used in academic publications/talks to illustrate the findings.
  * I understand that I can contact the researcher for this project by e-mail to receive more information and/or a summary of the results.



## Reflexivity

Please note: Some information below is included in the video for [Research Skills for data analysis](https://wtoivo.github.io/RM2-ODL-quali-book/data-analysis.html#optional-research-skills-session---preparing-for-data-analysis) as well

We ask you to think about your own position in the research as part of your report (there is a section in the methods!).

This can be quite tricky to do, but is very important for qualitative research. Some suggestions to get you started:

  * Think about the topic you are doing for your research and your position in it. Where would you place yourself in relation to it?
  * What are your own views on the topic? Do you feel quite strongly about it or not?
  
Write as you reflect. Writing – be it using pen or pencil on paper, typing on a keyboard, dictating to some voice capture device, or some other mode – is an important tool for developing reflexive depth. It is good to do this at various stages of the research process.

Start with your own experiences, understandings and views, but then also try to interrogate those (i.e. why do you have these particular understandings, views etc.?)

Some questions that you might ask yourself:

  * What do I expect to come up in the data? How does this relate to what we found?
  * What broader experiences have I had that might influence how I'm thinking about this?
  * What are my values (i.e. what is important to me)?
  * What about my beliefs? How might these have influenced my thinking?

Here we have some data from Braun & Clarke - there are different datasets to choose from. If you want to use the ones from Braun & Clarke, you can either choose the ['childfree'](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EWq1HW7Xm_BKnobsU_GRpcIBlSvnQ4k6XhFqBkszClAwWg?e=q4lc97) dataset or the ['healthy eating'](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EdfitbKwhodKo8Kmj9szNgwBNmt313A8dYknAiehHdy2lg?e=0vWOnu) dataset. However, we know that some topics might be difficult for people, so please do choose a topic of your own preference if you would rather  - any qualitative dataset (e.g.from UK Data Service) or news article would be fine.

### Activity 1

Spend about fifteen minutes reflecting on the topic and where you would place yourself in relation to it, both personally and more general views. Write as you reflect. Writing – be it using pen or pencil on paper, typing on a keyboard, dictating to some voice capture device, or
some other mode – is an important tool for developing reflexive depth. Start with your own experiences, understandings and views, but then also try to interrogate those.

Ask yourself questions like:

  * What assumptions am I basing my thinking on?
  * What broader experiences and values might inform my thinking on this?
  * How might these be connected to myself as a person, my various identities, my personal experience in relation to the topic, and the communities I am part of?

### Activity 2

Discuss your experiences of reflecting with your group. Did you find it easier than expected? Was it harder? Was there anything that surprised you about the process? Please only share what you feel comfortable with.

### Activity 3 (optional)

Ashley has some additional reflexivity probes and tips in her research skills session which can be accessed [HERE](https://wtoivo.github.io/RM2-ODL-quali-book/data-analysis.html#thinking-about-reflexivity)