# Group project 

## What is the group project?

In the group project, you will engage in three tasks that are designed to help you build your practical research skills in qualitative research. You will compile your answers to the tasks into a portfolio that you submit to Moodle as a group. Please watch this [video](https://uofglasgow.zoom.us/rec/share/hmdPpMhtl-PSRyrMqkveBUGXm-bbWmeDNrNhFiKFe4eXnWv4MHqnqwcEiPGVS6Rn._TyzV4uXqhP_jN7r) for an overview of the project, and make sure that you have engaged with the [AIS](https://sway.office.com/BusP6yjXtfZVeaB3?ref=Link) and [FIS](https://sway.office.com/41UBqJPistW5XL4G?ref=Link) of the group portfolio before starting any work on it so you know what to expect. 

[HERE](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EQM2Fzsi0FJAlDKTJXgi7-8Brm7ITIBw5ta3MaXSiDZfrg?e=FMLoM4) is a suggested timeline for the qualitative portfolio and report


## Getting to know each other in groups

This section is designed for you to engage with your group early, get to know each other, and develop some common guidelines for working together before you embark on the group project. If you haven't done so yet, please get in touch with your group now to complete the following activities. We have also provided a checklist of things to complete as a group before the start of semester 2.

### Getting organised in groups checklist:
  * Get in touch with group and make a group chat on Teams
  * Introduce yourselves
  * Post group introduction on RM2 channel
  * Set up a regular check-in time and/or meeting with group
  * Discuss group agreement and decide together on items to include
  * Submit group agreement to Moodle (individually)
  * Read effective group work document and discuss your strengths as a group
  * Download the group work template and assign tasks 

### Activity 1: Create a group chat and set up an initial meeting

Get in touch with your group and create a Teams chat. You **MUST** use Teams for all communication about the group project. Do not use any other platforms (such as Whatsapp, WeChat, Facebook etc.) as these can lead to people being excluded. Set up a meeting in which you will discuss Activity 3 from this chapter. After the initial meeting, set up a regular check-in time. This doesn't necessarily need to be a meeting every time, you can also do it over text. You will need to coordinate between time zones/work calendars/other responsibilities 

*DO:* Communicate regularly and be clear about where and how you are going to communicate about the group project. Be proactive if you are having a busy time and let your group know.

*DON'T:* Disappear and stop talking to your group if you're having a hard time (if something happens and you don't feel comfortable sharing with your group, you can let the course leads know). Don't agree to meeting times that don't suit you.

### Activity 2: Introductions

Introduce yourself to your group members on your Teams chat. In your introduction, tell your group where you are based, which parts of the degree you have enjoyed the most up to date and what is your favourite R function. As a group, find one *non-psychology/university related thing that you all have in common* and share that on the RM2 Teams channel in the thread. Bonus points for the most random common thing!

### Activity 3: Group agreements

We appreciate that group work can be challenging (and even more so if you are spread all over the World!) and we want to support you to have an enjoyable and educational group work experience. To that end, we would like each group to create a group agreement that all members sign. We also ask that you complete a task allocation and upload this with your agreement (they are in the same template). The purpose of this is for the group to come together and establish common ground and some rules that each of the group members is committed to. It also means that the group begins working with clearly allocated roles and tasks. This is not to mean that you cannot change tasks later, but it is helpful to set expectations from the outset. 

Download the group agreement template from [HERE](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EcRHw5yd3v1JmFwm1drRu-MB33Im0__d6jRPqKbdnjjDzg?e=s7wEoU). 

Then look at the list of potential items to include below, and as a group, discuss which items you want to include in addition to the standard ones provided, and if there are any you would like to edit or add outside of this list. You will be able to find a sample list of tasks to include for the task allocation in Appendix 1 within the template. 

Work on a collaborative document on OneDrive to create your group work agreement and task allocation, and once the group is happy with their agreement and initial tasks, each group member should submit it to Moodle individually (on the Formative Activities tile). ***Please submit your group agreement by the end of week 14 of semester 1.*** If you haven't submitted your agreements and task allocation, we will be in touch to check up on your group.

**Group agreement items**

Here is a list of items you may want to discuss with your group and add to the group agreement:

  * We all agree to establish a common timeline for the project and discuss any deviations from the timeline together as a group
  * We all agree to communicate with each other openly and honestly about the project and get in touch with the course leads in the event of an unsolvable group conflict.
  * We all agree to respect each other's individual ways of working and discuss these openly as a group. 
  * We all agree to respect diversity in our group. This includes cultural differences, neurodiversity, different work/life situations and may manifest in different ways of working/approaching tasks. 
  * We agree to discuss our strengths as a group and divide tasks accordingly.
  * I agree to stay in touch with the group and communicate as established by the group. If I am struggling and I do not feel comfortable sharing that with the group, I will get in touch with the course/programme leads for support
  * We all agree to meet on a regular basis as established by the group. If I cannot make a meeting I agree to communicate this openly with my group and get in touch to catch up about things I have missed.
  * We agree to plan out the individual contribution of each team member in advance before group work starting and openly communicate any changes that may arise during the project.
  * We agree to establish the best method of communication for our group that's inclusive and takes into account everybody's individual needs.
 
### Activity 4: Read the Effective Group work document

This document can be used as a checklist to do the group work for your qualitative portfolio. Give it a read and then discuss it with your group once you have your initial meeting. The effective group work guide can be found [HERE](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EZCuPb2m-MFMtAIGTAb2eM4B_ateTxqyR5X6YLceaL2Qcg?e=XeHk9h)

### Activity 5: Group work planner (optional)

You can access the planner template [HERE](https://tasks.office.com/gla.onmicrosoft.com/en-US/Home/Planner#/plantaskboard?groupId=07b6cc49-f02c-464d-a1f8-9a2c16e6b979&planId=XzmYoIr61k6qycSEWwbY6JYABfM1). We advise, although do not require, that you make one for your group, discuss the tasks together and assign them to members of your group. This is a good way to keep track of who is allocated to a task, and to modify tasks as required over the course of your project. 

Work back from the deadline to establish tasks and when they need to be done. Discuss your strengths and what each person in the group would like to do.

## Qualitative portfolio guidelines and materials

You will complete three tasks: Qualitative questions (Task 1a and 1b), Ethics (Task 2) and Terrible focus group (Task 3). Below, you will find information and the required materials to complete each task. Please use [THIS TEMPLATE](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EeFbaG-CE0pEnWBvsAwGIXUBIR8wAoFdJYYhklHoUKkEjg?e=DTA61b) to complete your submission.

### Task 1a: Qualitative questions

Below, you will find a brief overview of a study topic. In this task, we would like you to imagine that you are collecting data for this qualitative study. A variety of different data collection methods are possible (e.g. interview, focus group, open-ended survey questions). Thinking about the topic and research question presented below, please develop **SIX** questions that you would ask your participants to gather data on the topic of interest. Your questions should be open-ended, clear, concise and appropriate, and the order that they are presented in should make sense. Your aim is to develop questions that would be likely to generate open discussion and rich responses from participants.

**Please note: This section (1a) does not contribute towards the 1000 word count for the assessment.**

::: {.callout-note icon=false}

## Study overview

Universities  provide support for students, and this support can come in many forms,  from free counselling services to well-being advisors (Raunic &  Xenos, 2008).  

In one study, it was reported that only 3% of students used their university counselling service, and only 5% of those who were characterised as vulnerable based on questionnaire scores, used the services (Cooke  et al., 2006). This suggests that the majority of students did not make use of services available. 

 There are many reasons why students may not choose to seek help, including being unaware of services, low socio-economic status, being from different cultural background, embarrassment about having to seek help, and scepticism about the services (Eisenberg et al., 2007; Gulliver et al., 2010). 

Another  issue around seeking support is that many who do chose to get help,  have to wait long periods for appointments (Mowbray et al., 2006). In a  recent article reported  in the Independent, a waiting time of 4 months was cited for some  universities. These delays to support, can lead to emergence of mental  health crises situations. Unfortunately, in this the University of  Glasgow had one of the longest wait times for counselling  (Buchan, 2018).  

*Research question:  What are student’s views on how universities can support students and their mental health needs?*

:::


### Task 1b: Qualitative questions reflection

For task 1B, please reflect on your experience of generating the questions in task 1A. Do you think they would achieve what you want to achieve? Why or why not? Was it easier or harder than you expected? Please link to the evidence base in your answer (suggested word count: 250 words)


### Task 2: Ethics

With the Open Science movement, the use of Open, secondary datasets has become a more popular way of conducting research. You've learnt about the importance of Open data in terms of reproducibility and replicability for quantitative research in RM1 - however, the benefits and challenges of Open data are quite different in qualitative research and there are a number of ethical issues associated with sharing qualitative research data openly. For task 2 of your portfolio, we would like you to **identify one ethical issue** associated with the sharing and/or use of open qualitative data, and discuss why it is an issue, and how it could be mitigated. In your response, you should cite relevant literature on the use of open qualitative data, as well as the [BPS code of Ethics](https://cms.bps.org.uk/sites/default/files/2022-06/BPS%20Code%20of%20Human%20Research%20Ethics%20(1).pdf) (suggested word count 250 words)


### Task 3: Focus group gone wrong

Here is a short video from a fictional focus group that is conducted very badly (*please note this video is created only for the purposes of this assessment, is not from a real focus group, and should not be shared outside of this course!*).

Your task is to **identify two or three issues with how the focus group is run** and discuss why they are problematic and outline possible ways to improve them. In your response, you should cite relevant literature to support your ideas.

Access the Focus Group gone wrong recording [HERE](https://echo360.org.uk/media/f51c8477-94cd-4a0e-88a8-0a133dd8d21e/public)

### Where to get guidance for the portfolio tasks?

You should make sure you are up to date on Ashley's lectures on qualitative research. Further, some of the chapters in this book have activities and information which will be helpful in completing the portfolio:

  * [Chapter 2 on Qualitative questions](https://wtoivo.github.io/RM2-ODL-quali-book/qualitative-questions.html)
  * [Chapter 3 on Data collection](https://wtoivo.github.io/RM2-ODL-quali-book/data-collection.html)
  * [Chapter 5 on Ethics](https://wtoivo.github.io/RM2-ODL-quali-book/ethics-rigour-and-reflexivity.html) 

