# Academic writing

This chapter has some activities to help with your academic writing.

## Evaluation in introductions

The activities in this section are designed to help you improve your evaluation in the introduction of your RM2 report (and your dissertation). To re-cap from RM1, the purpose of your introduction is to provide a rationale for your study and answer the **WHY** question; why is your study worth doing? You want to sell your idea to the reader, using existing literature to show how you are building on the evidence that is there.

**Things to do and things to avoid**
  
  1. Avoid doing one study per paragraph – instead, build your arguments using multiple sources
  2. Avoid describing previous studies in a lot of detail – instead, show how your study builds on them
  3. Avoid critiques that your study cannot answer - instead, focus on aspects that your study will address
  4. Just because something is never done before, doesn't make it worth doing; show with evidence why we should do the study.

Here are paragraphs from an imaginary introduction to a qualitative study investigating postgraduate students' confidence in their zombie apocalypse survival.

For each, you can click on them to have a look in depth.

::: {.callout-caution icon=false collapse="true"}

## Show me Example 1: Using one source, writing descriptively

*A study by Lane and Karin (2011) looked at zombie apocalypse survival confidence levels in undergraduate students. The sample consisted of 25 participants (20 male and 5 female), recruited through convenience sampling. The study employed involved a survey comprising Likert-scale questions designed to measure participants' self-assessed confidence in various survival skills. Additionally, participants were asked about their exposure to zombie-related media. The data were subjected to t-tests and regression analyses, and the authors’ found that the biggest predictor of zombie apocalypse confidence was exposure to zombie-themed video games.*

This paragraph uses just one source, and describes the study in a lot of detail. Instead, it would be better to synthesise evidence from multiple studies and focus on what the findings mean, rather than being descriptive about the studies. Something like:

*A study by Lane and Karin (2011) found that the biggest predictor of zombie apocalypse survival confidence levels in undergraduate students was exposure to zombie-themed video games. Miller and Williams (2023) had similar findings, but exposure to zombie films was also a significant predictor of confidence. This suggests that simulation through media is an effective way to increase self-efficacy towards an unknown threat, which has also been found with alien attack research (Ripley, 2017).*

:::

::: {.callout-caution icon=false collapse="true"}

## Show me Example 2: Making criticisms that are outwith the scope of your study

*It should be noted that the majority of studies on zombie apocalypse survival confidence have looked at samples that consist of mostly men (Lane & Karin, 2011 but see also Grimes & Dixon, 2019), and that previous samples have been small.*

This paragraph makes a criticism that the study cannot address - issues with sample size are not something that we can address with qualitative designs. 

Instead, to create a stronger rationale, it would be better to focus your critical evaluation on aspects which your study actually builds on:

*While evidence on the behavioural predictors of zombie apocalypse confidence is robust, the majority of research (see Anderson, 2014) has focused on the exposure time to media and survival skills training. Hence, we lack understanding of how participants perceive their confidence beyond simulation experiences.*

:::

::: {.callout-caution icon=false collapse="true"}

## Show me Example 3: Why is your study worth doing?

*To date, there has been only one qualitative study on the topic – Seok (2013) collected data through semi-structured interviews, which were analysed using thematic analysis and two themes, “Survival mode” and “Confidence through skills” were identified. This study looked at undergraduate students; there is no previous literature on postgraduate students’ perceptions of their apocalyptic confidence. Therefore, this qualitative study investigates the perceived confidence of postgraduate students in their abilities to survive a zombie apocalypse.*

Just because it's never been looked at doesn't automatically mean it should be - show with evidence why and how you would expect your new sample/method/something else about the study to differ from previous research and why it's worth exploring:

*Previous research has looked at undergraduate students; however, it has been suggested that postgraduate students would be the group most at risk during a zombie apocalypse (Williams, 2021), but also that apocalyptic self-efficacy decreases with age (Anderson, 2004). This suggests that postgraduate students are the most mentally and physically vulnerable group during a zombie apocalypse, and hence it is important to understand their perceptions of apocalypse confidence, and the lack of thereof.*

:::

### Activity 1: RM1 feedback

Go back to your feedback from RM1 and see what your marker has said about the evaluation ILO and comments for your introduction. List two things that you did well, and two things you want to improve for RM2. If you would like to discuss the feedback and possible improvement points further, you can pop to Wil's or Ashley's office hours.

Quite often what we see is students engaging with a lot of literature in the intro (which is good!), but not really building a rationale or explaining with evidence why the study is worth doing. We want you to move beyond describing the research to critically evaluating it to show how your study expands on existing knowledge. 

### Activity 2: Top tips and rationales in published papers

**Tip 1: Show how your study builds on existing literature**
When you are building your rationale, try to use multiple studies to show your reader what the current context of the literature is, and how your study is expanding that knowledge. What new is your study bringing? How is it expanding on existing studies?

If you look at these paragraphs from Robertson et al. (2018), they are building the rationale for their study by showing how it expands on existing literature:

::: {.callout-note icon=false}

## Building a rationale

"Kerns and Kendall (2012) published an updated review of the prevalence of anxiety in individuals with ASD, and all studies fell within White et al. (2009)’s original range for anxiety symptoms (11–84%). It should be noted that, of the 24 studies included in the review, only two reported data for  individuals older than 19 years of age (Bakken et al., 2010, Hofvander et al., 2009), which illustrates the need to also focus on adults with ASD in future research (Howlin, 2000)."

"Secondly, as far as we are aware, there have been no qualitative studies investigating anxiety in autism using semi-structured interviews.  Although focus groups and interviews are both good data collection methods for qualitative data, there is evidence that individual  interviews tend to elicit a broader range of discussion points (Guest, Namey, Taylor, Eley, & McKenna, 2017). Again, this further extends the previous investigation conducted by Trembath et al. (2012)."
:::

**Tip 2: Focus your criticism**

When you are critically evaluating studies in your introduction, make  your criticism focused on things that your study is addressing. This  helps you build the rationale. For example, for the RM2 report, don't  focus on the sample size and generalisability of existing studies in your introduction, because these are not things that your study will actually be able to address. Instead, focus on gaps/problems your study can address.

If you look at this paragraph from Toivo & Scheepers (2019), they are identifying a gap/problem in existing literature and showing how the new study is addressing this:

::: {.callout-note icon=false}

## Focusing cricitism

"A potential issue in the above SCR studies (as well as in some of the  cognitive studies discussed earlier) is that the stimuli were not very  tightly controlled in terms of lexical variables (length, frequency,  abstractness, etc.), or in terms of syntactic/pragmatic complexity when multi-word phrases were used. This, again, introduces a number of  potential confounds (both within and across languages), making it  difficult to separate effects of emotional resonance from those related  to cognitive effort in word processing. In the present study, we aimed  at eliminating such potential confounds by matching our stimuli on a  number of lexical variables–as was done in the ERP studies discussed above [22, 23]–and by avoiding the use of translation equivalents."

:::

**Tip 3: Draw arguments from related topics. **

Sometimes if your topic has not been studied much, it might be difficult to create an evidence-based rationale for your research question. In this case, you can draw logical parallels from related topics/domains. Remember to explain to the reader why you would expect the findings to generalise across the related topics.

If you look at this paragraph from Mahrholz et al. (2018), it acknowledges that evidence on what they are looking at is scarce in voice perception, but the same effect has been found in face perception: 

::: {.callout-note icon=false}

## Drawing arguments from other topics

"Similarly, looking at reliability of personality traits across presentation durations, Willis and Todorov [40]  found that ratings of trustworthiness, competence, likeability,  aggressiveness, and attractiveness for faces, showed moderate to strong  positive correlations after 100 ms, 500 ms, and 1000 ms, when compared  to ratings made without time constraints. Only participants’ confidence  in their own judgements increased as a function of duration. Likewise,  again using photographs of faces, Bar et al. [33]  reported medium positive correlations between ratings at 39 ms and 1700  ms. The authors indicated that the lower threshold was sufficient for  reliable assessments of threat but not intelligence, supporting the  theory that rapid first impressions serve as a mean of self-preservation  and help determine appropriate approach-avoidance behaviour [1, 33, 38].  The idea being that it should not require much information to decide  whether a stranger is friend or foe. Finally, Todorov and colleagues [39]  obtained a similar finding, again for faces, showing 33 ms of exposure  to be sufficient to distinguish between trustworthy- and  untrustworthy-looking stimuli. Whilst correlations with control ratings  improved between 33 ms and 100 ms, increased exposure duration did not  significantly increase the correlations.

In voice research, though there are limited studies that consider the  reliability of personality judgements across varying lengths of stimulus  types, similar findings have been shown as in face research."
:::


### Activity 3: Active reading

When you are reading journal articles, make sure to take notes and think of how each article can be used to build your rationale in the introduction. Here is a resource you can use to help structure your notes about the studies you are going to use for your introduction: [INTRODUCTION NOTES DOCUMENT](https://gla-my.sharepoint.com/:w:/g/personal/wilhelmiina_toivo_glasgow_ac_uk/EXPNU5j4pQhKvRMYVx8dBvcBs85f4Z8q1V21wSokGOIbCA?e=eg7zd0)

## Evaluation in your analysis section

### Activity 1

Complete this to improve your evaluation for your thematic analysis, (as well as the discussion section). You may have already completed this as a part of your Data analysis chapter, but if you haven't please do it now. We ask you to compare two published papers against some of the qualitative report ILOs. You can access the activity [HERE](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EUiKwKgdqr1CsLeOxy5O42kBGNLxmbdeTqANFRu0caPcBA?e=BpEpBb)

### Activity 2: Going deeper in your analysis

One of the characteristics of a strong analysis section is that the writer demonstrates an ability to go beyond paraphrasing/summarising. This activity is designed to help you understand what might be involved in doing so. 

Read the following two extracts from an Analysis section and discuss these questions:

1. Which of the two examples is better? Why?
2. What have the authors done that makes the analysis better?


::: {.callout-note icon=false}

## Extract 1 - from a study about the impact of the COVID pandemic

Sarah spoke of using her leisure time to plan and fantasise about her wedding: 

*“it’s enough of a fantasy… it’s meant to be stressful, but it’s really just been fun. It’s like such a nice break from this humdrum life we’re living in right now” (Sarah: lines 459-461).*

Organising a significant life event seems to be viewed as granting Sarah an escape from her current monotony. While she refers to it as a “fantasy”, potentially given uncertainty of the pandemic’s progression, she appears to perceive this as constructive and realistic for her future self. Alternately, Mandy’s leisure activity involved impossible daydreams:

*“I started daydreaming more ridiculous stuff... I know it’s never going to come true ‘cause it’s not real, but it still entertains me” (Mandy: lines 443-444)*

While Mandy seems to be under no illusion that her daydreams are feasible, daydreaming impossible scenarios appears to provide more of a release than realistic situations that are subject to ever changing government regulations (e.g. travel bans) that may fall through.
:::


::: {.callout-note icon=false}

## Extract 2 - from a study about social media use during the pandemic

Some participants said it was difficult to fall asleep at night, including those who knew they should fall asleep but could not (*"if I can't stay up and can't sleep "- Sarah*), or participants subjectively thought that they did not need sleep or did not want to fall asleep (*"I am not really able to sleep at night, or like, sleep isn't really needed."* -Andrew)

Participants said that they used social media but that it was only positive at certain points:

*I feel like TikTok was fun in the first lockdown during the summer,'cause of all this summer content I guess, but after that it really went downhill. I don't know like, OK personally I deleted all my apps about three weeks ago* (John)

John tells us here that he deleted all his apps, because they all went ‘downhill’. Tik Tok was helpful during the first lockdown, but not after it.
:::


::: {.callout-caution icon=false collapse="true"}

## Show me the answer

Example 1 (COVID):  
This is the better example, because it goes beyond paraphrasing. The researcher is analysing the quotes and have engaged with the meaning behind the words. Each quote is selected in a way that helps the author build a narrative of what is happening in the data 

Example 2 (sleep): 
This is the weaker example, because the author just paraphrases what the participants say. This ends up not adding any real value in terms of analysis, because the reader could just read the quote. The narrative needs to analyse the data and show the reader why they interpret something in a particular way.  
:::


## Evaluation in discussions

In this section, we aim to provide some guidance about how to go beyond description in your writing. We will specifically focus on the Discussion section for your RM2 qualitative report here, but
you can apply this to other types of writing. In particular, it should be helpful for you as you proceed to your dissertation.

### What were your findings?
In your discussion section, start off by telling us what you found in your analysis. However, the key thing to think about here, in terms of evaluation, is to relate your findings to the wider research. It will be likely a good idea to consider on a theme by theme basis (if you are doing themes with no sub-themes) or on a subtheme basis (if you have one theme with 2-3 subthemes).

**Some things to consider:**
  
  * What did you find? What was your specific contribution?
  * Thinking about your findings, what are the similarities and differences from other research findings/theory? Why might this be the case?
  * Situate your findings within the broader context  - tell the reader about why your findings are important. This can help a reader understand the importance of the results.
  * Do your findings challenge existing research? If so, in what way? 
  * Can you bring in any critical thinking?
  
#### Activity 1

Read the paragraphs below (from Crompton et al., 2020) and think about what the authors are  communicating, with a view to considering the points above.

In particular, identify:

  * How the authors summarised their results
  * The contribution of the themes to the evidence base
  * How the authors discuss their results in relation to existing research
  * How the authors relate their findings to theory
  * How the authors link the findings to 'broader issues'
  
::: {.callout-note icon=false}

## Study 1: Crompton et al., 2020

This study aimed to examine the experiences of autistic adults spending time with autistic and non-autistic family and friends using a thematic analysis framework. Social relationships are an important, though often complicated, part of autistic people’s lives. Previous research has tended to focus on autistic people’s relationships with (assumed) non-autistic friends and family. Here, we specifically contrasted relationships across and within neurotypes. The analysis revealed three themes: cross-neurotype understanding, minority status and belonging. The themes help us understand why relationships between autistic and non-autistic people might be so challenging, and how relationships between autistic people are different.

The results align with previous research on the challenges that autistic people face when interacting with non-autistic others, but highlight that interactions with other autistic people are fundamentally different. All participants reported that spending time with non-autistic family and friends involved specific difficulties, which were not experienced when interacting with other autistic friends and family. This aligns with the double-empathy theory of autism which suggests that autistic and non-autistic people have a mutual difficulty in understanding and empathising with one another due to differences in how each person understands and experiences the world, rather than because of a communicative deficit on the part of the autistic person (Milton, 2012). Neurotypical people have been shown to overestimate how ego-centric their autistic family members are (Heasman & Gillespie, 2018), and overestimate how helpful they are to autistic people (Heasman & Gillespie, 2019). Our findings suggest that this translates into real-world difficulties in interactions with neurotypical friends and family that may affect the mental health, well-being and self-esteem of autistic people.

:::


### What are the implications of the study?

In addition to theoretical implications you would discuss in a quantitative study, there is scope to discuss broader implications here. Try not to go too far in these implications (e.g. saying that the NHS/University could make changes to how they run mental health services...this would require a much more extensive body of work).

**Some things to consider:**

  * How could these findings be applied to real-life situations?
  * What impact might this have for society in the future (even if with the caveat that it would depend on future research)?
  * Can you back up your assertions with reference to the literature? Arguments here are much stronger if you are able to cite papers to support.
  
#### Activity 2

Read the paragraph below from Robertson et al. (2018) and think about how the authors have communicated the implications of the research.

In particular, identify:

  * What the implications of the research are
  * How the authors link the findings to practical suggestions
  * How the authors back up these suggestions to the existing literature base
  
::: {.callout-note icon=false}

## Study 2: Robertson et al., 2018

There are a number of potential clinical applications for the findings detailed in this paper. They echo the modifications that are already undertaken for anxiety interventions designed for children and adolescents with ASD (Walters, Loades, & Russell, 2016). For example, it may be important to include support for individuals undertaking an intervention for their anxiety. This has already been identified as helpful in anxiety management interventions for children with ASD (Sofronoff et al., 2005), but the evidence here suggests that this might also be the case for adults. Furthermore, as adults reported feeling that they enjoyed interacting with other autistic people, it would be important to test whether running autism-only groups in terms of anxiety interventions helps outcomes or other aspects related to the feasibility of anxiety management programs (e.g. retention of participants).

:::

### Limitations

All research will have limitations  - there is never going to be a perfect study. Research is about weighing up the options and choosing the best design for the specific question we want to answer. Remember that qualitative research is not automatically limited because it is not quantitative. Therefore, be very careful not to use criteria we have for quantitative studies (e.g. generalisability, reliability, small sample sizes) and apply them to qualitative studies. Doing so would be similar to critiquing a behavioural study for not asking participants about their experience of interacting with the stimuli ;)

**Some things to consider:**

  * Do you think the quality, source, or types of data (or the analytic process) might have affected the methodological integrity in some way? If so, how?
  * Remember to link your limitations to the evidence base. This makes your argument much stronger than if you do not cite to back your points up.
  * If you want to mention generalisability, perhaps consider the concept of transferability instead, which is much more relevant to qualitative.
  * Try to aim for depth rather than breadth here - it's much stronger to have two points addressed comprehensively than have 12 limitations, each covered in a single sentence (you don't want to make your discussion section a limitations-fest!).
  
  
#### Activity 3

Read the paragraph below from Toivo & Scheepers (2019). Although this is not a qualitative paper, the following paragraph exhibits many of the strengths noted above.

In particular, identify:

  * What was the limitation observed?
  * How do the authors discuss this limitation, and consider the effect it might have had?
  * How do the authors back up their arguments with evidence from the literature base?
  
::: {.callout-note icon=false}

## Study 3: Toivo et al., 2019

One concern might be that we did not explicitly control for L2 proficiency in our sample of bilinguals, which is likely to affect cognitive effort in processing L2. However, all of our bilingual participants (a) self-reported to be highly proficient in English, (b) were Glasgow University students using English as their language of study, and (c) had been living in an English-speaking country for minimum of three months (average: two years and four months) when the study was conducted. Together with the fact that post-trial word recognition rates were well above 90% across participant groups and conditions (Fig 2), we do not believe that variation in L2 proficiency was large enough to have a major impact on our results. That said, we agree that proficiency should ideally be controlled for in future research, e.g. by adding a suitable measure as another person-specific covariate in the analyses. Previous research had identified proficiency as a potential mediating factor of perceived emotionality in the Bilingualism and Emotions Questionnaire [50], and it had also been suggested that bilinguals with close-to-native proficiency in L2 show similar affective processing in L1 and L2 [19].

:::



### Anything else?

The points above are the key components that we would expect to see in a Discussion section, with some guidance on how to go beyond description. However, you might also consider strengths and future research. It's also good to include a brief conclusion. You won't have the word count available to go into the same detail as in these papers, so try to use the examples above to really focus on what you can incorporate within your Discussion section to strengthen your evaluative writing.




