# Frequently Asked Questions 

This page was last updated 11th Feb 2025

## General Project questions

**How do the portfolio and qualitative report work together - should we focus on one before looking at the other?**
The qualitative portfolio is designed to support you in developing skills that would be important for actually running qualitative studies (e.g. reflexivity, developing questions, awareness of ethics, awareness of good/bad practice for data collection). The report is designed to support you in developing your data analysis skills and then writing up this information into a report.

Re. the timescales - we would advise that you start working (or at least thinking about) the qualitative report before your qualitative portfolio is handed in. However, we realise everyone is different and prefer to work in different ways. We have developed a timeline for the summative assessment with suggested milestones, although you should revise these deadlines to find something that works for you.

## Qualitative portfolio questions

### General portfolio questions

**Where can I find information about the qualitative portfolio?**
You can find information about the portfolio in the template, the guidelines, the AIS and the video Wil recorded. You can access the materials in [chapter 6](https://wtoivo.github.io/RM2-ODL-quali-book/group-project.html) of this book.

**What is the word count for each section?**
This is in the template, but it can be broken down as follows: Activity 1a (no word limit for the six questions), Activity 1b (250 words), Activity 2 (250 words), Activity 3 (500 words).

**In the answers, should we use or avoid acronyms such as BPS and GDPR?**
Usually in your writing you should avoid unnecessary abbreviations unless they are really commonly used, as this makes it harder for the reader to follow your writing. A good general rule of thumb is not to come up with any abbreviations yourself. These two are very common for the context of your assignment so you can use them (this will also help with the word count which is very limited here).

**Do we need to set out an introduction and concluding summary in our responses to each of the sections?**
You don't need this - you can dive straight in :)

**Is it okay for us to take what a study says at face value (i.e. the study says x, which backs up the point)? Or do we have to be critical about the study?**
Yes, this is fine - we expect you to use the studies to support the points you are making, rather than critically interrogating how well the study supports the claim. It would not really be possible to do the latter within the word count. This assessment is a bit different to when you are writing a report, for example, where you'd want to show how you are building on the existing literature (to help support your rationale)

**I can't figure out how to cite the BPS code; examples online are both "BPS,2021" and "Oates et al., 2021"**
Cite it as BPS.

**Is it okay to answer the questions or do we have to make a unique contribution (as you do in an essay or a report)?**
Just doing what you are asked is fine. This is not the same type of assessment as a report or essay as it is focusing on skills needed to run a project, so it will be assessing different things.

**Should I delete the included instructions from the template document so it's just the headings for each section?**
Either keeping them or deleting them is fine - whichever you prefer.

**Can I use guidelines and and strategies for qualitative research from fields other than psychology?**
Yes, perfectly fine to use these guidelines - you don't have to stick to Psychology. Just make sure that the guidelines apply to the type of research methodology/RQ you are discussing.

**Is slight variability in word count between the sections allowed as long as the final product is less than 1000?**
Yes, there is slight variability allowed - it is overall 1000 but you can change the distribution that is suggested slightly (however, try not to change by more than 30-40 words so you provide the right amount of detail for each section).

### Task 1: Qualitative questions & reflection

**To what extent can we refine the sample? The RQ refers to 'students', but could we specify that further by limiting it to only students who have / not sought out mental health support?**
Yes, if you want to limit it further, this is fine - we kept it somewhat flexible on purpose so you have a bit of freedom with this.

**What sort of evidence is relevant in a reflection? Is it related to the topic (i.e. of mental health) or is it more about the anticipated problems / other researchers protocol in similar research? Or a bit of both? Should we avoid trying to justify our choices in the reflection, or is that a good thing to do?**
I think it would make sense if it's more related to methods rather than the topic choice - would be quite good to justify your choices in the reflection.

**Would it be a good idea to include a warm up question/ice breaker and a closing question in our six questions?**
For the purposes of this assessment, we would suggest just sticking to the six main questions (i.e. not using up two of these for a warm up/exit question). This is because we ask for a limited number, and that way we can keep things consistent across the whole class. One thing you might want to consider is your placement of questions (i.e. the order in which you would ask them).

**What is the difference between an interview and a qualitative survey?**
Interview is where the researcher is one-to-one with a participant and asks them questions. Qualitative survey is a qualitative questionnaire that is often sent to participants online and they fill it out in writing.

**How does (evidence based) reflection differ (if at all) from (evidence based) writing that we have been doing so far for our assignments?**
It doesn't really - we want you to look at the evidence and back up your ideas with relevant sources. The portfolio materials have some probes for your reflection. In the ethics task you should also use the BPS code of ethics and refer to that as well.

**For activity 1, do we would need to pick a specific topic area (from the evidence base) to explore in more depth in order to frame our questions?**
The overall topic and research question is given to you in the materials, and then you need to come up with focus group/interview/qualitative survey questions that you would ask the participants to investigate the research question

**Should we mark some of the questions as priority with a star, to note the ones that we would ask first if time was running short in the focus group?**
You can asterisk the ones you deem most important if you want to, but there is no requirement to do so either (so basically, whichever you prefer)

**Can we include prompts underneath some of the questions?**
You can if you want, but we ask you to stick to a maximum of one prompt per question if you do this (and that it's really clear for the reader what the main question is and what the prompt is)

**Is there scope to include visual prompts in our questions?**
Theoretically yes, although we've never seen this asked before so wouldn't know what a visual prompt would look like. If you want to include this, it might be worth contacting Ashley / Wil to show them an example.

**What should we focus our reflection on? About half of the word count in our reflection is currently taken up by an evidence-based discussion of why we opted for the FG format over the interview as this really guided how we constructed the questions thereafter. I just want to know if such a focus is correct or if you're looking for discussion to centre more around a specific question or two that we chose?**

There is no one correct way to structure the reflection. We are interested in how you found the experience and why you made the decisions that you did in constructing your list of questions. We often see reflections on why people chose a particular approach for their questions too (e.g. focus group over interview/survey).

**You have advised that we choose 1 or 2 issues and go into their depth when answering the questions on ethics and the terrible FG. What do you recommend we do for the reflections on the questions in task 1? Do we for instance speak about why we chose a specific approach over the other? Why we chose these specific questions? Challenges we faced etc. Or do we combine everything? Now, we have 250 words of a general reflection on FGs, guideline designing on the topic under discussion, challenges we faced, and what we couldn't get with citations of course. I'm wondering if we should be more focused and try to answer only 1 point?**
Basically, we don't specify what you can and can't reflect on, so as long as it's relevant (which this is), then you have some flexibility :) It is a very open question and we are anticipating lots of different ways of answering this one in particular. The main thing is to follow the guidelines that have been given and to look at the ILOs, to see how well you think your response is meeting them

**Is it appropriate to briefly describe our own expertise and experiences, and how they've informed our decisions? Would this count as reflexivity and would you like to see evidence of reflexivity? Or would you rather we didn't talk about ourselves directly?**
Yes, this would be completely appropriate to discuss as part of reflexivity. It's fine to discuss yourselves directly (but it is not the only way to do this task). You would be reflecting on why you made the choices you did and would be demonstrating what experiences you have that went into those. Be mindful to make this evidence-based too!

**We have included a short rationale on why we chose a focus group which is placed before the six questions. Will this short paragraph be included within the word count for the whole portfolio or will it not count as part of the 1000 words?**
A rationale (if you choose to include it) should be in 1b. The only thing not included in the word count within the activities themselves is the actual questions of Activity 1a

**Do prompts/probes have to be phrased as a question or can they be more of a statement?**
They will usually be framed as a question but it is fine to write them as a statement for this assignment if you prefer. 

**Do we need to define terms such as open-ended questions?**
No, there isn't space for this within the word count for this particular assignment

**If we're including our group member's experiences for reflexivity, should we name them, or just refer to them as 'group member'?**
You can either use initials or "group member", either one would be fine

**Within the questions we are setting for our group project - would it be appropriate to name "University of Glasgow" for instance or would it be best to keep to just "University" in general?**
We would suggest just sticking to University, rather than specifying the University of Glasgow in particular.

**is it OK to assume that the participants work in the same university as its important for a point we've made in the moderating?**
Yes, this is fine :)


### Task 2: Ethics

**Should we connect our answer to Question 2 to what we did for Q1?**
No, there is no expectation that Activity 2 is linked to Activity 1 (although Activites 1a and 1b need to be linked to each other).

**Can you tell us where people tend to go most wrong in this particular question?**
Sometimes, groups will focus more on ethical issues that are relevant for quantitative research, or research in general, rather than specifically thinking about qualitative research. This is something that is best avoided as it doesn't answer the question that is set. 

### Task 3: Focus group gone wrong

**For focus group, do we have to back the issue with specific observations from the video? E.g @ 4.05min X did what, which is an issue because...**
No, this would likely take up too many words. 

**Is there a preference for either moderator or facilitator?**
No, these are interchangeable and either is fine

**Are we to only quote peer reviewed literature in support of our argument, or can we quote for example from the Braun and Clarke book?**
No, it's fine to cite Braun & Clarke and there might also be guides/opinion pieces etc. - these would also be fine to use in support. Also, it's fine to use older evidence too - we do realise there's unlikely to be lots of 2022/2023 papers out there on how to do a focus
group! We have also included some additional papers on the reading list (under Thinking about the focus group) to give a bit of a start (although please note we haven't had time to read these...we've skimmed through)


**We have identified the point we want to talk about. For example, it is about the moderator's part. Should we focus on the moderator's issue in general or pick a couple of specific examples of bad moderating and write about them in depth? Because the word count is limited, it isn't apparent what strategy to pursue.**
Either is fine to be honest. You could pick moderating as one issue and then another one. Or you could focus on two separate parts of moderation. My main suggestion
would be to pick an approach that allows you to go into depth on the issue, explaining why it is a problem, what could be improved etc.

**I’m struggling with how to approach the focus group task- do you have any examples excellent or ‘A’ standard work?**
We don't provide exemplars, because this assessment is specific so it would be really hard to do that without giving out the answers. In terms of what the focus group task is asking, please make sure you read the ILOs for this assessment that can be found on the AIS document. The only ILO specific for the FG task is:

Correctly identify TWO or THREE issues present in the focus group, explain why they are problematic, and discuss possible improvements (#3: Focus group), which means that you should identify what is wrong in how the focus group is conducted (this is mostly based on what the moderator is/isn't doing), explain why these things are not good when you are conducting a FG, and explain how they could approach this instead.

To meet the other ILOs for this task, you should make sure you write clearly and concisely and demonstrate evaluation in your answer (this is an ILO for all your assessments you have done to date and means that you need to use evidence to build your arguments and go beyond description). For this task evaluation should include you explaining why your chosen issues are bad practice when conducting a focus group, and citing some evidence (this will mostly be methodological in nature) to back up your answer.


**For the focus group task, do we need to include quotes from the transcript when referring to the issues?**
No, we would advise that you don't do this, as it will take up a lot of the (very limited!) word count. Instead of quoting, just say what the participant/facilitator did that you think explains the issue you have identified.

**When I'm evaluating a study, do you want me to criticise it? Do you want me to talk about the methodology?**
For this assessment, we aren't really looking for you to criticise the studies that you are using - for example, for the focus group task, it's more about explaining why it's a bad thing that the moderator is doing and then using some evidence to back that up (e.g. some guidance for how to run a focus group or if there's a paper saying what you might want to do to make your participants feel more comfortable). Here, it's not about saying 'here's this study, it had x participants' - that is more for the report, where you are building a rationale.

**Would a good structure be: x happened, x is bad for y reason, z should be done instead (with studies to back up)?**
There are different ways that you can structure it but the above example would be fine. The main thing is that you are covering what we ask of you in the guidance and the ILOs.

**Should we include timestamps of when something happened in the video?**
No, this is not necessary to include - just telling us what you've identified will be fine

**A lot of the literature is pretty old. What should I do?**
We are aware that some of the literature is older, and it's completely fine to use this. It's not the same type of assessment as essays/reports etc., and lot of the guidance is from the 90s or so.

**Do we refer to the participants in the terrible video by their names eg: Ashley, Gaby? Or we call them participant 1, 2, 3, or the moderator (or Wilhelmina) did this with a participant, and that with another participant?**
I think generally I would say 'a participant' etc. as it depersonalises it. However, you do have the names there as they were on the video and - as we haven't given any guidance specifically on this - it won't affect the marking in any way if you use our names.

## Qualitative report questions

### General report questions

**Will there be detailed guidance about each section of the qual report?**
Yes, we have a guidance in this book in the qualitative report section in [chapter 8](https://wtoivo.github.io/RM2-ODL-quali-book/qualitative-report.html), which will cover the key points to cover in the report.

**Is our report written in a specific style, e.g. IPA, thematic analysis etc?**
You will use thematic analysis to analyse your data. We covered this in detail in the lectures in semester 1, and we will also have activities to support this in semester 2.

**How many interviews should we select for our report?**
We ask that you choose a maximum of three interviews to analyse (less than this is fine if you have enough data within your chosen interviews)

**I'm not sure what all the different tasks are for the report - where can we find this information?**
We haven't shared an explicit task list for the report and one reason for that is because RM2 is purposefully designed to get you to work a bit more independently in preparation for the dissertation.

Key stages are as follows:

* Familiarise yourself with what is expected for the report assignment have a look at the data and decide which dataset you want to work with
* Look at the data in more detail - which interviews will you select?
* Look at relevant literature and start to think about your RQ think about the rationale for the study
* Conduct your Thematic Analysis
* Write up the study as a full research report (which will be similar to your RM1 report).

**For the report, I am unclear on the criteria for choosing transcripts. I have an approximate idea of a RQ and looking at the transcripts they could be broadly grouped into 2 sets relating to how the participant responds to the questions. Is the intention to choose transcripts that have a consistent thread or that cover a diverse range of views? With only 3 transcripts I'm not sure if it should be based on commonalities or if this is kind of cherry picking?**
I would say it's about choosing transcripts that you will be able to analyse and are relevant to the specific research question that you have. So, it would make sense to pick transcripts that are relevant (i.e. they cover the issue you are interested in). They may or may not have the same perspective - I think either would be okay to be honest. Sometimes, it can be useful to have different views as you can then think about why (which can be interesting in terms of evaluation of your themes) and it's also fine to have more consistent views too.

**Can I do a different analysis and not TA?**
For the RM2 project we unfortunately only have assessment guidance and support for doing a thematic analysis (Braun &Clarke's version) and we currently are unable to expand that to different type of analyses - this is because it's an introductory qualitative course so the same way as in RM1 you were asked to do a specific analysis on the data, we would like you to stick with TA for the individual report.

**What voice should I write in? Should my reflexivity be written in first person?**
APA style encourages the use of active voice instead of passive voice ("I did" instead of "it was done"). You can use either but make sure to be consistent and don't make your sentences overly complicated. For reflexivity, you should definitely use "I", because it is about your own reflection in regards to the RQ and the data

**Should I be writing my report as though I designed and conducted the interviews etc myself?**
You should not write it as if you collected the data - you should write it as a secondary data analysis.

**I've found published papers that are using the same dataset and I'm worried that my research is the exact same/doesn't add anything new? I feel that I should mention these original reports when I'm setting my study in the wider literature, but I'm not sure how then to argue that my study is adding anything new if I acknowledge these reports - what should I do?**
The chances of your RQ and all other parameters of the study being identical are not very high; if your RQ is worded exactly the same as a published paper, you may wish to tweak it a little bit to focus on a more specific aspect of the data, so you can explain in the introduction how it adds to existing literature. Also look out for what kind of analysis they did - then you can discuss why TA might be better suited for your RQ/the type of data you have. What subsample of interviews did they use and is yours different? If so, why? It doesn't need to be an entirely different thing to what is already published; good science is built in incremental steps, so think about what are the things that are different in your study to the published papers, and how that adds to what we already know

### Research questions

**Do you have any tips for how to arrive at your research question for the qualitative report?**
This book has a section on developing RQs - work through those activities first. I would probably have a look over some of the datasets and decide what you'd like to focus on in terms of topic. Then I'd think about what kind of information you get from them (e.g. is it people's opinions/experiences/beliefs etc.) and what you'd be interested in looking at specifically.

**Should our questions be broad enough so we can use the whole transcripts or should we narrow them to focus on specfic areas? I think an obvious example to illustrate what I mean would be on the Life limiting transcripts and then having a question of something like "experiences of animals on wellbeing etc" but that would then heavily focus the content of the analysis on one of the sub areas of the transcript and a lot (but not all) might be irrelevant?** 
Perfectly fine to narrow them to focus on specific areas, but with this I would say make sure that you have enough data about your specific RQ to be able to analyse it. You don't have to use the whole transcript by any means - completely fine to use subsections. It's possible to revise your RQ in thematic analysis, so - if you were unsure - you could start off broader and then could make it a bit more specific down the line. There is the caveat that this would affect your intro, as you build towards why you've chosen this research question in your rationale.

**Can we post more than one RQ on the padlet if we're not sure what route to go down?**
Yes, this is fine - you can post a few and we can give feedback on these (let us know if you have a favourite though)

**Does the research question have to be tailored towards one of the questions asked in the interview or can it be broader?**
It's probably better to be broader - generally, themes will tend to be broader than a single question that is asked and it might be a little on the specific side

### Introduction & Discussion

**Should we include a mini paragraph at the start of the introduction summarising the research question at the end?**
We would recommend to avoid it for this specific assignment, as this might make it difficult for you to have a broad-to-narrow structure and could cause unnecessary repetition.

**In the discussion section, can we refer to the data (e.g. the participants) or if that is too detailed for this section?**

**Two of the interviewees I have picked agree on something whilst the other disagrees so was going to specifically refer to this. Or should I be picking up the broader theme that came out in the discussion section and don't need to reference the specific point I am referring to?**
In the discussion you should focus on the themes and discuss them in relation to existing literature/future literature instead of focusing on individual comments from your participants (these you should analyse in the analysis section). If you think back to quant, you are not talking about the specific numbers in the discussion but instead focus on what the findings mean and how they build on existing literature. Sometimes in quali literature you see papers that have a sort of combined analysis and discussion section, in which case they might combine individual quotes and existing literature, but for this assignment we are asking you to separate them to two different sections for clarity and to make it a bit simpler for you to structure.

**Do limitations/future directions need to be separate sections?**
They don't need to be two separate paragraphs - often what is a limitation to a study can logically be addressed in the next study.

### Method

**How to choose my theoretical framework and where does it go?**

**I take it that we are meant to indicate if we are using a constructionist or realist/experientialist framework for the analysis.  Are we free to choose this or are there any recommendations? I would assume that focusing on semantic themes is more doable given the limited word count?  Also, where would we state this? In the methods section or at the start of the analysis?**
It would be good to explain which theoretical perspective you are coming from, yes. It's important to take the word limit into account, so it could well be the case that focusing at a semantic level will be more doable  - the key thing in your analysis is that you try to go beyond description, and develop a narrative. If you include details about the framework, this should be done in the Methods section, rather than at the start of the analysis.

**Is there an easy guide to working out what theoretical approach you are using? I understand the difference between realism, social constructionism etc in theory but I can’t work out how to apply it to my work. I kind of think it could be any of them so I think I’m missing something!**
It's more about thinking about your own perspective (rather than the dataset), as you are correct - any of the different approaches could be applied to the dataset. You could focus on what type of knowledge you are looking for, or instead, think about epistemology/ontology (or both!). It's sometimes easier to think about the type of knowledge you want to obtain - if it is knowing more about people's experiences, and how they describe their world, then that would be about seeking out phenomenological knowledge. If it is more in terms of uncovering something concrete that happens in the world (i.e. a truth) then it would be more realist that you are looking for.  If you have questions about the theoretical approach specifically, feel free to pop into any of Ashley's office hours for a chat

**Also can we draw upon our personal experiences in the report?**

**I'm looking at the LGBT+ dataset and also work in an NHS trust; I've seen some transphobic actions happen at work and was wondering if this is appropriate to talk about in the report if appropriate for the RQ**
Yes, there is a section for reflexivity in the methods section, where you should reflect on your experiences and how you felt about the topic/your experiences. You can also expand on it a bit in the discussion if you want.

**Are there good examples we can have a look at for reference in terms of reflexivity?** 

**I'm looking through the list of examples studies you have included using thematic analysis, and I don't think they include any form of reflexivity at least not in the method section, or am I missing something? Or would this be done during analysis?**
Here are some resources to help, but they are not so much examples of reflexivity sections within papers and - instead - are more about giving guidance. Here are some
links to start you off:

* Barrett et al (2020): How to...be reflexive when conducting qualitative research
* McLaughlan et al (2012): Phenomenological analysis of patient experiences of medical student teaching encounters (they embedded reflexivity within the 'Analysis' section of the methods
* Blog by Jacqui Burne: https://nzareblog.wordpress.com/2017/11/28/self-reflexivity/
* Byrne (2022) A worked example of Braun and Clarke's approach to reflexive thematic analysis
* Examples of reflective commentary from online resources from 'Reflexive Thematic
* Analysis' (2022) by Braun & Clarke: https://study.sagepub.com/thematicanalysis/
student-resources/chapter-3/understanding-the-process (this website has a lot of really useful resources - the book is available through the library)

**Are we meant to be using literature to support our reflexivity like we did for the group project reflection?**
You don't need to do this - reflexivity for a specific research project is more about thinking about your own positionality and how that might have affected the way you approached your data so it doesn't need to be supported with evidence.

**Do we need to report the specific questions that we used to extract our results? I mean of course I read the full 3 interviews, however my topic was very specific and it was located in two specific questions in the interviews. Do I need to report that? Furthermore do I need to report all the questions of the interview anyways? I see all the qualitative studies report the full set of the questions.**
You can add them as an appendix but you don't need to list them all in the methods section; there you can just describe generally what kind of questions they were asked.

### Analysis

**Do I need to cite literature in my analysis section?**

**According to Braun and Clarke (2013) a good analysis section will link back to relevant research previously done on the topic (i.e citations to link it to the wider literature) however,  I would presume that this will be better suited to the discussion section of our project given the word count? Or should we cite previous research to link our themes within the analysis section?**
Qual reports are written in one of two ways: 1) where the analysis and discussion are in separate sections  - in the analysis, you report your findings, in the discussion, you link your findings to the literature, identify limitations etc. 2) you have a joint analysis and discussion section, where you both present your results and link them to the research. Braun & Clarke are talking about the second, whereas we're doing the first option. So, no, just focus on presenting your themes in the analysis section - like with the quant report, you will then have a separate Discussion section where you link to the literature

**In the thematic analysis, what should we do if two participants give opposite answers for the same questions. How do we deal with that conflicts?**
This can make for a really interesting analysis and discussion section! You should explain the theme for
the reader, and provide context for the different views presented by the participants. You can find more information in the Braun & Clarke (2013) book

**In the interview transcripts came across a nice statement I would like to quote, however the statement was made by the interviewer not the participant. The participant agreed with the interviewers statement. Would it be appropriate to quote the interviewer in this instance?**
It might depend on what the statement is and the context. So, for example, is it a) the researcher summarising what the participant said and then the participant agreeing or b) the researcher giving their own opinion about it and the participant agreeing? I'd be more likely to say this is okay to include if it was the first than the second, I think. If you were to include it, it would probably be best to a) make sure that there's enough context surrounding this (i.e. what was there in the lead up to it and also afterwards?), and b) only do this sparingly.

**Can one of my themes be my RQ or an interview question?**
No, you should try to go a bit deeper in finding meanings in the data in your analysis. If you end up with a theme that is actually your RQ or one of the interview questions, you have *summarised* the data rather than *analysing* it. This is surprisingly easy to do by accident so don't feel bad if this has happened to you - just go back to the data and look a bit further. What aspects of the RQ does the theme capture? What specifically do the participants say about it?

**Can we use a mixture of inductive and deductive approach?**

**Actually I started exploring the data without any previous thoughts (inductive) and later I started reading the literature for this topic and unintentionally I started observing some of the same conclusions in my data (deductive). Is this a formal way of analysing the data? Can I report a mixture of approaches?**
It is possible to do this - [here is an example of a paper](https://journals.sagepub.com/doi/10.1177/160940690600500107#) that used a combination of inductive and deductive coding for TA. This would not be the only way to do it, but is an overview of one possible way in which coding and developing themes could utilise both. My main suggestion would be to be clear with the reader in your methods about the thinking behind your approach.

**What if in our analysis we end up developing different themes the three interviews? Do we have to report only the common themes or is it ok if we also analyse themes that are evident only in one or two interviews?**
Ideally at the themes stage you should consider the dataset as a whole so most of your themes should come from more than one interview  Try to find quotes which illustrate the theme not just from one participant. Sometimes themes may be more strongly present in parts of the data and that's ok but try to avoid having one theme that's from one participant only and another one that's from another participant - the themes should represent the data a bit more holistically

**What if I develop more than two themes - can I mention the other themes in my analysis section?**
You can briefly say that you developed more themes but don't waste your word count on explaining them in more detail or talking about the codes related to them. In terms of the discussion, you should focus on the two themes you have chosen and developed a full narrative for (the same way in quant you would not discuss an analysis you did not actually finish) and connect those to existing literature. You can talk about the other stuff as future directions if you would like

**Should the themes be presented in a hierarchical way related with each other? **

**What if we detect themes that are not related with each other? Do we include data that don't fit anywhere else or if they are trivial we can exclude them from the final**
It depends on how you identify your themes - they may be strongly related to each other and hierarchical and they may not. There is no one correct way. In the report writing guide, we ask that you report a maximum of two themes (or one theme with 2-3 subthemes) so I would choose those where you would be able to go into the most depth in terms of interpretation report?


