---
title: "Setting expectations for dissertation students"
editor: visual
---

I provide some information for students before dissertation supervision starts, so that they know how I work as a supervisor, what they can expect from supervision from me, and also what my expectations are from them as supervisees.

## Overview

Hello, and welcome to your dissertation! As you know, I'm Ashley and I'll be your dissertation supervisor this year.

Every dissertation project is different, and the way I tend to supervise is to focus on us working together (both you and I, and also us as a group with your peers) to support you to develop a range of skills, culminating in your dissertation write up. I tend to be quite structured as a supervisor, and this is one reason I developed this document, as it will outline the process for you in advance, so you know what to expect. If there is something you would like added, let me know and I'll see what I can do.

## Expectations

I have certain expectations in terms of how we will work together over the academic year. I have some below, but in our first group meeting, I will ask you to think about whether there are any you would like to add, or if there is anything you want to amend related to the points below.

### Communication

I ask that all students working with me communicate with me, letting me know if they are unable to make a certain deadline or if something gets in the way of a task they had planned for a specific point in time. In return, I will communicate with you regularly, including when you can expect feedback, and will do my best to let you know if I have to delay something beyond what I had previously communicated.

### Attendance

I ask that all students attend group sessions unless there is something urgent that has come up. Individual sessions are more flexible and can be cancelled if you feel that you don't need to meet in a particular week (although please let me know in advance if this is the case). Group sessions are held for 1h every fortnight, with individual sessions being 30 mins, held in the weeks that we are not meeting as a group.

### Supportive space

I want the dissertation group to be an encouraging, safe, space and the dissertation process to be an enjoyable (albeit challenging at points!) experience for everyone. This means that you should never hesitate to ask any questions (all questions are valid) and I'd like us all to work together to support each other. No one is perfect and we will all make mistakes during the process (including me). I've been supervising for quite a few years now and I haven't yet managed to come across anything that we have been unable to sort after some discussion, so don't worry about talking to me if something has gone wrong :).

## Dissertation meetings

Dissertation meetings will be held every week, with individual meetings and group meetings alternating on a weekly basis.

**Semester 1**

-   Group meetings (1 hour): Weeks 1, 3, 5, 7, 9, 11

-   Individual meetings (30 mins): Weeks 2, 4, 6, 8, 10, 12

**Semester 2**

-   Group meetings (1 hour): Weeks 1, 3, 5, 7, 9 (plus a 1.5h session in week 11)

-   Individual meetings (30 mins): Weeks 2, 4, 6, 8, 10

All meetings will be held in my office. I will send outlook invitations for all supervisions, so that they are in Outlook calendars.

We will most likely have to select a different time for Semesters 1 and 2, due to changes in timetables/teaching, but can revisit this nearer to the end of Semester 1.

**Semester 1 group meeting time**: Wednesdays 12-1pm

**Semester 2 group meeting time**: Wednesdays 11am-12pm

## Deadlines

We will set deadlines for you to submit the following: proposal, ethics, introduction, methods, results/analysis. I will ask you to work with me to set these deadlines so that we agree them together.

### Ethics

We will prioritise the ethics application from the very start - the reason for this is that you cannot recruit data unless you have your ethics approved, meaning that delayed applications can bring a project to a halt.

### Dissertation

Dissertation section deadlines are not set in stone - I would much rather that you take an extra day or two if you need it rather than sending an unfinished draft (with the caveat that it will never be perfect). If this is the case, let me know and we can discuss options.

Although it is unusual for this to be an issue, there will be a point where I am no longer able to look over drafts before the deadline. We will aim for dates before this, but my cut-off is that **I don't accept drafts once we reach 1st March**. This is because it becomes very unlikely that I will be able to turn around feedback in time for you to be able to make meaningful changes by the submission .deadline in mid-March.

## Communication

I have set up a Teams with a couple of channels that you can access - I have a General one for all of my dissertation students and your Level 4 (24-25) one (which we will use most of the time).

Please direct message me (rather than email) with your ethics documents, proposal, and any draft dissertation sections.

Most questions should be posted in the teams channel - if you have something that is personal and therefore not appropriate to be shared with the whole team, then it is okay to DM. I prefer DM on teams over email, as my email inbox is harder to keep on top of.

## Feedback

### When you can expect feedback

For ethics and the proposal, feedback will tend to be returned within a few days or a week. For dissertation section drafts, I will usually aim to provide feedback within two weeks. This is because drafts tend to be in semester 2, when I have most of my teaching. Depending on my teaching/marking commitments, this may take longer, but I will communicate with you about this at the time. You will also be able to see where you are in the 'feedback queue' in the shared deadlines document.

### What type of feedback you will receive

I generally provide in-text comments, so that I can show you which part am I referring to in my feedback (where relevant). I will also give a global overview/summary. I will tend to focus on what can be improved, as this is the priority to help your writing develop. However, I will also let you know what you do well too.

### How you can ask for specific feedback

If you have specific parts you would like feedback on (e.g. if you are unsure about something), you can leave comments in your document (either at specific points or at the start) and I will respond to them when I am reading through. Try not to put the points you'd like feedback on in the message when you send the file to me, as I put the files elsewhere and don't tend to refer back to messages. This makes it more likely that I'll miss them if they aren't contained in the document when I come to read it.

### What format should be sent for the drafts?

All documents (proposal, ethics, Intro, Methods, Results/Analysis) should be in Word. An exception to this is copies of standardised measures (this might be in pdf, which is fine).

## Supervision sessions

### Group Sessions

In each session, there will be time for questions and we will also go round the group and see how everyone's project is going. We will also spend time discussing certain aspects of the dissertation, and I will provide resources as appropriate.

I have planned out the group sessions as follows (although these are subject to change if required):

**Semester 1**

-   Week 1: Getting to know each other, topics, proposals

-   Week 3: Ethics, research questions

-   Week 5: Summarising papers, bullet point introductions

-   Week 7: Discussing the bullet point intros, participant recruitment, reducing perfectionism

-   Week 9: Collecting data, developing evaluation (intro)

-   Week 11: Structure (i.e. reverse outlines), JARS guidelines

**Semester 2**

-   Week 1: Receiving and applying feedback, presenting work

-   Week 3: Analysis (quant and qual)

-   Week 5: Developing evaluation (discussion), linking in theory

-   Week 7: No-stakes presentations - everyone will present a 5 min summary of study findings so far (these can be very roughand initial if you haven't completed analysis)

-   Week 9: Final group session - bring your questions

-   Week 11: Longer session: Celebration combined with practice talks for the UG conference/BPS conference

### Individual sessions

Individual sessions are dedicated slots each fortnight for you. Here, we will tend to catch up on how your project is going, and you will have the opportunity to ask questions. These may be used more often at certain points in the year (e.g. getting ethics together) than others (e.g. once your data collection is all set up).

Most people come along every week, but if you find one week that you don't need to meet, it's not an issue - just let me know and we can cancel it.

## Peer Review

I am not allowed to look at a draft of the Discussion section, so there will be the opportunity to peer review each others' discussion sections. We will discuss this in Semester 2, in the group sessions.

I will provide some guidelines around peer review, and you can choose whether to take part or not. I am happy to set things up for you if you want, or can take a step back and you can organise within yourselves. Everyone who wants to take part must be included.

## Future aspirations

I realise that some people get a bit nervous when asked the 'what are your plans after graduation?' question, but I will ask you about this at some point during semester 1. I will most likely do this in individual supervision. The reason that I do it is so that I can see if there is anything I/your peers can do throughout the dissertation process to support your future plans.

If you don't know what you want to do, this is also fine, but it is then about seeing if we can maximise development of your employability skills, which will then be helpful in whichever direction you decide to go in :).
