---
title: "Semester 1 Week 5"
editor: visual
---

## Summarising papers, writing, bullet point introductions

In this session, we cover summarising papers as well as general writing advice before specifically covering bullet point introductions. I then ask students to bring a bullet point introduction with them into the Semester 1 Week 7 session.

I've made some [notes for this session](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EeTpe8KOecFNvPUzETtY3U8B34TUuXe1Ogy6ZFNDAbTPcw?e=EMHCKI). Feel free to use/adapt etc. as you wish.

### Expected progress

-   By now, I would be expecting to see some ethics drafts coming in and all projects should be firmed up. Rationales should all be submitted.

### Summarising papers

-   I cover some suggestions that I have on how to summarise papers
    -   Summarise with intent (what is the purpose?)
    -   Pull out the key details (remember can go back for further detail)
    -   Take notes for the Discussion, even when reading for the Introduction
    -   Further details are linked in the document in *Internal Resources*

### General writing advice

-   Writing advice will likely differ from supervisor to supervisor. Here are some of my suggestions (rest are in the document linked previously):
    -   It's better to write something than nothing
    -   Know what works for you (e.g. timing, accountability, blocking time out)
    -   Small goals can be helpful
    -   Split out **generation** and **editing**
        -   This can help get over the hurdle of the 'perfect' sentence

### Bullet point introductions

-   I discuss that I would like everyone to write a bullet point introduction for the next session. I tell students that I do not expect this to be perfect, and that it can change down the line
-   We go through some of the suggestions I have for writing this.
-   I ask students to post on the Teams channel before the next group meeting (in two weeks time) but others may choose a different process
-   I signpost them to [Wil's resource](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EXHOBRvN14dLoThMX6zBEd0B7dxgXh3t7zcUhc5H7CSOjw?e=HeDnPs) on developing a rationale for their introduction.

## Internal resources

[My suggestions](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EeTpe8KOecFNvPUzETtY3U8B34TUuXe1Ogy6ZFNDAbTPcw?e=EMHCKI) on summarising papers, writing in general, and developing a bullet point intro

[Wil's resource](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EXHOBRvN14dLoThMX6zBEd0B7dxgXh3t7zcUhc5H7CSOjw?e=HeDnPs) on developing a rationale

[General writing tips for quantitative research](https://bartlettje.github.io/RM1_Resources/Resources.html) (from the RM1 team): (Chapters 17-25)

[General writing tips for qualitative research](https://wtoivo.github.io/RM2-ODL-quali-book/academic-writing.html) (from the RM2 team)

## External resources

Here's an example of a template for summarising a paper, which can be helpful for students if they want some guidance on where to start.

[Document link](https://teachpsychscience.org/index.php/a-guide-and-template-for-taking-notes-on-research/815/communicating-science/)
