---
title: "Semester 2 Week 1"
editor: visual
---

## Receiving and applying feedback, presenting work

In this session, we see where everyone is now that we are back for Semester 2 (and the deadline will suddenly be just over two months away!). I cover receiving and applying feedback in this session, as well as presentation research.

At the end of the session, I tell students that the next group session is on analysis and ask them to bring any questions they have in for the session so we can cover them together.

### Expected progress

-   Students should have submitted or be not too far off submitting a draft of the Introduction for feedback. They should also be working on their Methods.
-   Students should be recruiting participants by now

### Receiving and applying feedback

-   As part of the group session, I talk about [the type of feedback I give](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/Ead4D1hp_7FOi4TlUVQA_O4B9dZcvARaCYuyIWtw3uO0MA?e=K2rR0W) (i.e. what students can expect when they receive feedback from me).
-   I also tell them how they can get the most out of the feedback that I give (e.g. asking questions after receiving it, leaving comments in their work for me to respond to)
-   This will be individual to each supervisor, but I've provided a summary of what I discuss with the students below. I don't give them this, but it has the main things I talk about in the discussion.
-   I cover a few, select, parts of the external resources linked below and we discuss how they might be able to apply these to their work in semester 2.

### Presentations

-   I've noticed that quite a few students I supervise are nervous about presenting, so I talk to them about how they feel about it.
-   We discuss presenting their dissertation research, and I encourage them to take the opportunity to present when they get it. Although it can be anxiety provoking, it helps equip them with useful employability skills
-   I then highlight the Level 4 conference at the end of the semester, and the BPS conference that is usually at the end of March/beginning of April. I tell students that to support these, we will a) practice running through findings in the group (week 7) and we will b) book out a room to do a proper practice with slides (week 11). Both of these are no stakes and the purpose is to help students practice communicating their research in a safe environment.
-   We then discuss [some of my tips](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EQh-1I7HCsBGkpcK6WmxPUUB_7JmqoRw1LINLhLWATig6w?e=veACdI) for this (caveat: others may disagree) and together we plan out some concrete actions of what they could do to improve their experiences of presenting.

## Internal resources

[Guidance on the type of feedback I tend to give for dissertations](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/Ead4D1hp_7FOi4TlUVQA_O4B9dZcvARaCYuyIWtw3uO0MA?e=K2rR0W)

[Guidance on presentations](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EQh-1I7HCsBGkpcK6WmxPUUB_7JmqoRw1LINLhLWATig6w?e=2AYZfm)

[Useful resources on feedback](https://moodle.gla.ac.uk/course/view.php?id=4529&section=5) in the Psychology & Neuroscience General Information moodle, including a [Feedback and Study Guide](https://moodle.gla.ac.uk/mod/book/view.php?id=1076576).

## Extenal resources

There are a few useful resources targeted at helping students get the most from feedback. We can't cover it all, so I tend to show students some parts of how to practically apply feedback in group supervision and we discuss it (e.g. SNOB analysis in the Salford document, Action Planning in the 'AdvanceHE Student Guide).

I always highlight that they are in fourth year and so will be used to applying feedback, but that it can be useful to consider how they might further improve things.

[Hepplestone et al., 2010](https://s3.eu-west-2.amazonaws.com/assets.creode.advancehe-document-manager/documents/hea/private/tfa_student_guide_1568036746.pdf)

[HEAdvance resource, August 2012](https://s3.eu-west-2.amazonaws.com/assets.creode.advancehe-document-manager/documents/hea/private/resources/10_feedback_resources_for_your_students2_1568036613.pdf)

[Salford Uni resource](https://www.salford.ac.uk/sites/default/files/2019-12/Making-the-Most-of-Feedback.pdf)

[Portsmouth Uni](https://www.port.ac.uk/student-life/help-and-advice/study-skills/speaking-skills-and-presentations) have some useful tips on presenting for students
