---
title: "Semester 2 Week 11"
editor: visual
---

## Celebration and practice for the Undergraduate conference 

**This session is longer than usual - I usually book a room for two hours and schedule it for an hour and a half**

-   Mid-way through Semester 2, I will arrange a time that works for everyone and then book a room (Seminar room, Boyd Orr) to do live run-throughs of the talks for the L4 conference.
-   We usually practice whichever format they will do at the conference
    -   Some will do 5 min lightning talks, others 10 min scientific talks.
    -   If someone has a panel, I will run through some practice questions with them.
    -   If someone has opted for the written submission, I ask them to take us through what they've chosen to do
-   I then give feedback on slides/pace/delivery etc. so that the students get some additional practice before the L4 conference itself.
-   There is also a chance for the students to reflect on how far they've come over the year (I try to bring cakes in so they have a chance to celebrate)
