---
title: "Semester 2 Week 7"
editor: visual
---

## No-stakes presentations

In this session, I ask the students to come prepared to present five minutes on their findings. If they have results to present, they can summarise these. If they haven't completed their analysis, then they should present on what they've done so far and are planning to do.

I then ask students to ask questions of each other, so that they can practice asking questions and the student presenting gets practice in responding to questions. This tends to take up the whole session, so I don't plan anything else alongside this.

I will also remind students about the peer review of the Discussion section if they haven't yet mentioned organising this concretely.

### Expected progress

-   By week 7, students will be around 3-4 weeks away from submitting
-   I should have most Analysis/Results sections sent to me for feedback by now and make sure students are aware of the last date they can send me drafts (extenuating circumstances aside)
-   If students haven't written up their Analysis sections, they should be well underway with analysis
